### PR TITLE
Restructure data model to consume Statutes and Subsections

### PR DESCRIPTION
**Pull request by ghickman**
This restructures a few models to better consume the SUDGT spreadsheet,
specifically:

Statute:
Represents a piece of Legislation, e.g. the NHS Act 2006

SubSection:
Represents a part of the related Statute, e.g. 6D Regulations relating
to EU obligations.

LawfulBasis:
Represents a high level basis for doing something, it does not specify
what this something is (see LegalJustification).  It is a short title
and description which can cover multiple SubSections.

LegalJustification:
Represents the Lawful Bases under which an OrgType can perform an
Activity.

This also adds some new importer commands to pull in various bits of
data from the sheets separately.  Most notably OrgTypes are consumed
from the `organisations.csv` without consuming the rest of the CSV.
OrgTypes are required for two different sets of data but there is no
source of truth for them.  So this importer picks `organisations.csv` and
works from there.

### CODE REVIEW

**Comment by fredkingham** [comment]
https://github.com/nhsengland/phmi/pull/91/files#diff-36787bb95d754bee292513a50c589b42R386 looks like it has no link

https://github.com/nhsengland/phmi/pull/91/files#diff-36787bb95d754bee292513a50c589b42R412
looks like it expects a link

**Comment by fredkingham** [comment]
/activities/allocating-risk-scores-and-stratifying-populations

```
Cannot resolve keyword 'legaljustification' into field. Choices are: data_types, functions, id, index, lawful_bases, legal_justifications, name, orgs, slug
```

**Comment by fredkingham** [comment]
apart from that I think we're good to go

**Comment by ghickman** [comment]
@fredkingham – thanks! I completely forgot to check that detail page, it's very broken, fixing now!

**Pull request merged**
